### ISSUE TITLE
New crasher in driver

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#1001]
I can't say for certain what is causing this crasher. But, I can reliably crash my driver with some objects.

I did the gdb and here are the results:

```gdb
terminate called after throwing an instance of 'char const*'

Thread 1 "driver" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a74859 in __GI_abort () at abort.c:79
#2  0x00007ffff7e4c8d1 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7e5837c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7e57359 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7e57d11 in __gxx_personality_v0 () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7c54bff in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007ffff7c555ba in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x0000555555577e1e in <lambda()>::operator() (__closure=<optimized out>)
    at /frogdice/thresh/fluffos/src/comm.cc:1109
#9  scope_guard::detail::scope_guard<process_input(interactive_t*, char*)::<lambda()>, scope_guard::detail::on_exit_policy>::~scope_guard (this=<optimized out>, this=<optimized out>)
    at /frogdice/thresh/fluffos/src/thirdparty/scope_guard/scope_guard.hpp:232
#10 process_input (ip=<optimized out>, user_command=<optimized out>) at /frogdice/thresh/fluffos/src/comm.cc:1109
#11 0x00005555556a5a6b in process_user_command (ip=0x7ffff1e26900) at /frogdice/thresh/fluffos/src/comm.cc:1198
#12 (anonymous namespace)::on_user_command (fd=<optimized out>, what=<optimized out>, arg=0x7ffff1e26900)
    at /frogdice/thresh/fluffos/src/comm.cc:94
#13 0x00005555555a5393 in event_process_active_single_queue.isra.0.lto_priv.0 (base=0x7ffff4cdff00,
    max_to_process=<optimized out>, endtime=0x0, activeq=<optimized out>)
    at /frogdice/thresh/fluffos/src/thirdparty/libevent/event.c:1727
#14 0x00005555555a93a7 in event_process_active (base=0x7ffff4cdff00)
    at /frogdice/thresh/fluffos/src/thirdparty/libevent/event.c:1819
#15 0x00005555555937f0 in event_base_loop.constprop.0 (base=base@entry=0x7ffff4cdff00, flags=0)
    at /frogdice/thresh/fluffos/src/thirdparty/libevent/event.c:2068
#16 0x00005555556e1742 in backend (base=0x7ffff4cdff00) at /frogdice/thresh/fluffos/src/backend.cc:239
#17 driver_main (argc=2, argv=0x7fffffffdca8) at /frogdice/thresh/fluffos/src/mainlib.cc:441
#18 0x000055555557e34d in main (argc=<optimized out>, argv=<optimized out>) at /frogdice/thresh/fluffos/src/main.cc:5
(gdb) info locals
set = {__val = {0, 6920625286979520000, 0, 0, 3545020643498688048, 3690464806024540473, 7087924491762619304,
    4962311462336433886, 1, 13979173243358019584, 579005069656919567, 283686952306183, 98784445207, 0, 0,
    1658172386723233792}}
pid = <optimized out>
tid = <optimized out>
ret = <optimized out>
(gdb)
```

**Comment by thefallentree** [comment]
#1002
