### ISSUE TITLE
Crasher when trying to sprintf some illegal value

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#1082]
I'm going to be honest, I'm not exactly sure what it's trying to print with sprintf. Because printing it crashes the driver.

But, I did the gdb and I got this

```
Thread 1 "driver" received signal SIGSEGV, Segmentation fault.
0x0000555555627fa2 in svalue_to_string (obj=0x7ffff4b4cf38, outbuf=0x7fffffffa330, indent=4, trailing=1, indent2=<optimized out>) at /home/gesslar/mud/lpu/fluffos/src/packages/core/sprintf.cc:380
380             outbuf_addv(outbuf, "0x%hhx,\n", (char)obj->u.buf->item[i]);
(gdb) bt
#0  0x0000555555627fa2 in svalue_to_string (obj=0x7ffff4b4cf38, outbuf=0x7fffffffa330, indent=4, trailing=1, indent2=<optimized out>)
    at /home/gesslar/mud/lpu/fluffos/src/packages/core/sprintf.cc:380
#1  0x0000555555627f04 in svalue_to_string (obj=0x5555557fcb00 <_ZL6_stack.lto_priv.0+512>, outbuf=0x7fffffffa330, indent=0,
    trailing=0, indent2=<optimized out>) at /home/gesslar/mud/lpu/fluffos/src/packages/core/sprintf.cc:450
#2  0x0000555555629be6 in string_print_formatted (
    format_str=0x7ffff4a83d98 "[2024-07-17 21:44:07] (WSS ECHO) [/std/daemon/websocket_client.c:websocket_connect:74] Server: %O",
    argc=1, argv=0x5555557fcb00 <_ZL6_stack.lto_priv.0+512>) at /home/gesslar/mud/lpu/fluffos/src/packages/core/sprintf.cc:1039
#3  0x000055555561abda in string_print_formatted (argv=0x5555557fcb00 <_ZL6_stack.lto_priv.0+512>, argc=<optimized out>,
    format_str=<optimized out>) at /home/gesslar/mud/lpu/fluffos/src/packages/core/sprintf.cc:787
#4  f_sprintf () at /home/gesslar/mud/lpu/fluffos/src/packages/core/efuns_main.cc:2501
#5  0x000055555559b641 in eval_instruction (p=<optimized out>)
    at /home/gesslar/mud/lpu/fluffos/src/vm/internal/base/interpret.cc:3981
#6  0x000055555559a55c in eval_instruction (p=<optimized out>)
    at /home/gesslar/mud/lpu/fluffos/src/vm/internal/base/interpret.cc:3826
#7  0x00005555555b4d7a in apply_low (fun=<optimized out>, ob=0x7ffff4b06980, num_arg=0)
    at /home/gesslar/mud/lpu/fluffos/src/vm/internal/apply.cc:332
#8  0x00005555555b50f0 in apply (where=<optimized out>, num_arg=0, ob=<optimized out>, fun=<optimized out>)
    at /home/gesslar/mud/lpu/fluffos/src/vm/internal/apply.cc:358
#9  safe_apply (fun=<optimized out>, ob=<optimized out>, num_arg=0, where=<optimized out>)
    at /home/gesslar/mud/lpu/fluffos/src/vm/internal/apply.cc:387
#10 0x00005555556013de in call_out (cop=<optimized out>) at /home/gesslar/mud/lpu/fluffos/src/packages/core/call_out.cc:250
#11 0x00005555555cddc7 in std::function<void ()>::operator()() const (this=0x7ffff2537628)
    at /usr/include/c++/11/bits/std_function.h:590
#12 (anonymous namespace)::call_tick_events () at /home/gesslar/mud/lpu/fluffos/src/backend.cc:137
#13 (anonymous namespace)::on_game_tick (arg=0x55555596e440 <(anonymous namespace)::g_ev_tick>)
    at /home/gesslar/mud/lpu/fluffos/src/backend.cc:145
#14 0x00005555556aecc1 in event_process_active_single_queue (base=base@entry=0x7ffff4a26f00, activeq=<optimized out>,
    max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0)
    at /home/gesslar/mud/lpu/fluffos/src/thirdparty/libevent/event.c:1727
#15 0x00005555556aef9f in event_process_active (base=0x7ffff4a26f00)
    at /home/gesslar/mud/lpu/fluffos/src/thirdparty/libevent/event.c:1819
#16 0x00005555556d5960 in event_base_loop.constprop.1.isra.0 (base=0x7ffff4a26f00, flags=0)
    at /home/gesslar/mud/lpu/fluffos/src/thirdparty/libevent/event.c:2068
#17 0x00005555556e68ef in backend (base=0x7ffff4a26f00) at /home/gesslar/mud/lpu/fluffos/src/backend.cc:239
#18 driver_main.isra.0 (argc=2, argv=<optimized out>) at /home/gesslar/mud/lpu/fluffos/src/mainlib.cc:441
#19 0x000055555557d88d in main (argc=<optimized out>, argv=<optimized out>) at /home/gesslar/mud/lpu/fluffos/src/main.cc:5
```
```
(gdb) info locals
i = 3887064
```

**Comment by gesslar** [comment]
I found it!

```
> eval printf("%O\n", string_encode("moo", "UTF-8"))
Evaluating: printf("%O\n", string_encode("moo", "UTF-8"))

BUFFER ( /* sizeof() == 3 */
  0x6d,
  0x6f,
  0x6f
)
Result = 0
> eval printf("%O\n", allocate_buffer(1))
Evaluating: printf("%O\n", allocate_buffer(1))

BUFFER ( /* sizeof() == 1 */
  0x0
)
Result = 0
> eval printf("%O\n", allocate_buffer(0))
    
[ ALERT ] - Socket got disconnected.
            Reason: The remote host closed the connection
[ INFO ]  - Connection time: 00:01:05.337
```
