### ISSUE TITLE
crasher when snooping

### ISSUE THREAD

**Issue by staun** [fluffos/fluffos#643]
Hey,

Found this driver crasher yesterday when I tried to snoop a fellow wizard to help him use the 'admtool' on LIMA. Driver was recompiled with ENABLE_SANITIZER=ON  but refuses to crash when I do that, so back to no sanitizer.

It was reproduced on two different servers with LIMA setups.

```
Eval interrupted: object obj/secure/snoop_dummy#46 cost limit reached, limit: 2000000 usec.
Stack trace (most recent call last):
#13   Object "", at 0xffffffffffffffff, in
#12   Object "/pack/fluff2019/bin/driver", at 0x55812c228bf9, in _start
#11   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fa96dee5e0a, in __libc_start_main
#10   Source "/home/staun/thefallentree/fluff2019/fluffos/src/main.cc", line 5, in int main(int argc, char **argv) [0x55812c228bb8]
          2: extern "C" {
          3: int driver_main(int argc, char **argv);
          4: }
      >   5: int main(int argc, char **argv) { driver_main(argc, argv); }
#9  | Source "/home/staun/thefallentree/fluff2019/fluffos/src/mainlib.cc", line 413, in backend(event_base *base)
    |   411:   debug_message("Initializations complete.\n\n");
    |   412:   setup_signal_handlers();
    | > 413:   backend(base);
    |   414:
    |   415:   return 0;
      Source "/home/staun/thefallentree/fluff2019/fluffos/src/backend.cc", line 224, in int driver_main(int argc, char **argv) [0x55812c32d799]
        221:   auto t = gametick_timeval();
        222:   event_add(g_ev_tick, &t);
        223:
      > 224:   try {
        225:     event_base_loop(base, 0);
        226:   } catch (...) {  // catch everything
        227:     fatal("BUG: jumped out of event loop!");
#8    Object "/lib/x86_64-linux-gnu/libevent-2.1.so.7", at 0x7fa96d85024e, in event_base_loop
#7    Object "/lib/x86_64-linux-gnu/libevent-2.1.so.7", at 0x7fa96d84f784, in
#6    Object "/lib/x86_64-linux-gnu/libevent-2.1.so.7", at 0x7fa96d84571b, in
#5    Source "/home/staun/thefallentree/fluff2019/fluffos/src/comm.cc", line 745, in get_user_data(interactive_t *ip) [0x55812c335d14]
        742:         /* handle snooping - snooper does not see type-ahead due to
        743:          telnet being in linemode */
        744:         if (!(ip->iflags & NOECHO)) {
      > 745:           handle_snoop(ip->text + start, ip->text_end - start, ip);
        746:         }
        747:
        748:         // search for command.
#4  | Source "/home/staun/thefallentree/fluff2019/fluffos/src/comm.cc", line 1488, in receive_snoop(char *buf, int len, object_t *snooper)
    |  1487: #ifndef NO_SNOOP
    | >1488: static void receive_snoop(const char *buf, int len, object_t *snooper) {
    |  1489:   /* command giver no longer set to snooper */
    |  1490:   if (CONFIG_INT(__RC_RECEIVE_SNOOP__)) {
    | Source "/home/staun/thefallentree/fluff2019/fluffos/src/comm.cc", line 1497, in apply(char *fun, object_t *ob, int num_arg, int where)
    |  1495:     str[len] = 0;
    |  1496:     push_malloced_string(str);
    | >1497:     apply(APPLY_RECEIVE_SNOOP, snooper, 1, ORIGIN_DRIVER);
    |  1498:   } else {
    |  1499:     /* snoop output is now % in all cases */
      Source "/home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/apply.cc", line 296, in receive_snoop(char *buf, int len, object_t *snooper) [0x55812c334fcd]
        293: #ifdef DEBUG
        294:   expected_sp = sp - num_arg;
        295: #endif
      > 296:   if (apply_low(fun, ob, num_arg) == 0) {
        297:     return nullptr;
        298:   }
        299:   free_svalue(&apply_ret_value, "sapply");
#3    Source "/home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/apply.cc", line 270, in int apply_low(char *fun, object_t *ob, int num_arg) [0x55812c2e1055]
        267: #ifdef DEBUG
        268:     save_csp = csp;
        269: #endif
      > 270:     call_program(current_prog, funp->address);
        271:     DEBUG_CHECK(save_csp - 1 != csp, "Bad csp after execution in apply_low.\n");
        272:     return 1;
        273:   }
#2    Source "/home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/base/interpret.cc", line 1889, in eval_instruction(char *p) [0x55812c2fa879]
       1886:                     current_object->obname, max_eval_cost);
       1887:       set_eval(max_eval_cost);
       1888:       max_eval_error = 1;
      >1889:       error("Too long evaluation. Execution aborted.\n");
       1890:     }
       1891:     /*
       1892:      * Execute current instruction. Note that all functions callable from
#1    Source "/home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/simulate.cc", line 1950, in error(char *fmt) [0x55812c2c978b]
       1947:   vsnprintf(err_buf + 1, 2046, fmt, args);
       1948:   va_end(args);
       1949:   err_buf[0] = '*'; /* all system errors get a * at the start */
      >1950:   error_handler(err_buf);
       1951: }
       1952:
       1953: void do_message(svalue_t *lclass, svalue_t *msg, array_t *scope, array_t *exclude, int recurse) {
#0    Source "/home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/simulate.cc", line 1834, in error_handler(char *err) [0x55812c2c9439]
       1831: #ifndef NO_ENVIRONMENT
       1832:   restrict_destruct = nullptr;
       1833: #endif
      >1834:   num_objects_this_thread = 0; /* reset the count */
       1835:
       1836:   if (((current_error_context->save_csp + 1)->framekind & FRAME_MASK) == FRAME_CATCH) {
       1837:     /* user catches this error */
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault
```

snoop_dummy.c mentioned above is:
```
/* Do not remove the headers from this file! see /USAGE for more info. */

object *snoopers = ({});
string buf = "";
string header;

void remove()
{
  if(sizeof(snoopers)) 
    {
      error("can't remove while in use.\n");
    }
  destruct();
}

void create(string name)
{
  header = name + "% ";
}

object *get_snoopers()
{
  if(previous_object() != find_object(SNOOP_D))
    {
      return;
    }
  return snoopers;
}

void add_snooper(object snooper)
{
  if(previous_object() != find_object(SNOOP_D))
    {
      return;
    }
  snoopers += ({ snooper });
}

void remove_snooper(object snooper)
{
  if(previous_object() != find_object(SNOOP_D))
    {
      return;
    }
  snoopers -= ({ snooper });
  if(!sizeof(snoopers))
    {
      remove();
    }
}

void receive_snoop(string s)
{
  if(!strlen(s)) return;
  // the m is part of a control sequence for some people
  if(s[<1] == '\n' || (s[<1] == 'm' && strsrch(s,"\n")!=-1))
    {
      snoopers->receive_private_msg(header + buf + s);
      buf = "";
    }
  else
    {
      buf += s;
    }
}
```

After a while I managed to crash it while running under gdb, here's the backtrace:
```
Eval interrupted: object obj/secure/snoop_dummy#46 cost limit reached, limit: 2000000 usec.

Program received signal SIGSEGV, Segmentation fault.
error_handler (err=0x7fffffffbaa0 "*Too long evaluation. Execution aborted.\n") at /home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/simulate.cc:1836
warning: Source file is more recent than executable.
1836      if (((current_error_context->save_csp + 1)->framekind & FRAME_MASK) == FRAME_CATCH) {
(gdb) bt
#0  error_handler (err=0x7fffffffbaa0 "*Too long evaluation. Execution aborted.\n") at /home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/simulate.cc:1836
#1  0x000055555561878c in error (fmt=<optimized out>) at /home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/simulate.cc:1950
#2  0x000055555564987a in eval_instruction (p=<optimized out>) at /home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/base/interpret.cc:1889
#3  0x0000555555630056 in apply_low (fun=<optimized out>, ob=<optimized out>, num_arg=<optimized out>) at /home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/apply.cc:270
#4  0x0000555555683fce in apply (num_arg=1, where=1, ob=0x7ffff5064940, fun=0x555555740ea2 "receive_snoop") at /home/staun/thefallentree/fluff2019/fluffos/src/vm/internal/apply.cc:286
#5  receive_snoop (snooper=0x7ffff5064940, len=3, buf=0x7ffff394e0c0 "l\r\nnights") at /home/staun/thefallentree/fluff2019/fluffos/src/comm.cc:1497
#6  receive_snoop (buf=0x7ffff394e0c0 "l\r\nnights", len=3, snooper=0x7ffff5064940) at /home/staun/thefallentree/fluff2019/fluffos/src/comm.cc:1488
#7  0x0000555555684d15 in get_user_data (ip=0x7ffff394e000) at /home/staun/thefallentree/fluff2019/fluffos/src/comm.cc:745
#8  0x00007ffff743371c in ?? () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#9  0x00007ffff743d785 in ?? () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#10 0x00007ffff743e24f in event_base_loop () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#11 0x000055555567c79a in backend (base=0x7ffff50a3000) at /home/staun/thefallentree/fluff2019/fluffos/src/backend.cc:225
#12 driver_main (argc=<optimized out>, argv=<optimized out>) at /home/staun/thefallentree/fluff2019/fluffos/src/mainlib.cc:413
#13 0x0000555555577bb9 in main (argc=<optimized out>, argv=<optimized out>) at /home/staun/thefallentree/fluff2019/fluffos/src/main.cc:5
```

**Comment by staun** [comment]
Pull latest v2019, recompile and test it again?

**Comment by thefallentree** [comment]
yep
