### ISSUE TITLE
Segmentation fault - 2019 running on WSL2 Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#672]
```
Full Command Line: /frogdice/thresh_fluffos/bin/driver /frogdice/thresh_fluffos/bin/config.mud3333
Boot Time: Sat Oct 10 16:30:21 2020
Version: fluffos v2019.2020091001 (Linux/x86-64)
Jemalloc Version: 5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756
ICU Version: 66.1
libdw or libbfd is not found, you will only get very limited crash stacktrace.
Core Dump: No, Max FD: 1024
========================================================================
Processing config file: /frogdice/thresh_fluffos/bin/config.mud3333
*Warning: obsolete line in config file, please delete:
        address server ip
*Warning: obsolete line in config file, please delete:
        address server port
*Warning: obsolete line in config file, please delete:
        reserved size
*Warning: obsolete line in config file, please delete:
        binary directory
*Warning: obsolete line in config file, please delete:
        swap file
==== Runtime Config Table ====
time to clean up: 600
time to reset: 900 (new: 1800)
time to swap: 300 (new: 3600)
evaluator stack size: 65536 (new: 2000)
inherit chain size: 30
maximum evaluation cost: 30000000 (new: 50000000)
maximum local variables: 64 (invalid new value: 500) (new: 255)
maximum call depth: 150 (new: 30)
maximum array size: 15000
maximum buffer size: 400000 (new: 200000)
maximum mapping size: 150000 (new: 15000)
maximum string length: 200000
maximum bits in a bitfield: 12000 (new: 1200)
maximum byte transfer: 200000 (new: 10000)
maximum read file size: 200000
hash table size: 7001 (new: 3067)
object table size: 1501 (new: 383)
living hash table size: 256 (new: 89)
gametick msec: 1000
heartbeat interval msec: 1000
sane explode string: 1
reversible explode string: 0
sane sorting: 1
warn tab: 0
wombles: 0
call other type check: 0
call other warn: 0
mudlib error handler: 1
no resets: 0
lazy resets: 0
randomized resets: 1
no ansi: 1
strip before process input: 1
this_player in call_out: 1
trace: 1
trace code: 0
interactive catch tell: 0
receive snoop: 1
snoop shadowed: 0
reverse defer: 0
has console: 1
noninteractive stderr write: 0
trap crashes: 1
old type behavior: 0
old range behavior: 0
warn old range behavior: 1
suppress argument warnings: 1
enable_commands call init: 1
sprintf add_justified ignore ANSI colors: 1
call_out(0) nest level: 1000
trace lpc execution context: 0
trace lpc instructions: 0
enable mxp: 0 (new: 1)
enable gmcp: 0 (new: 1)
enable zmp: 0 (new: 1)
enable mssp: 1
==============================
Initializing internal stuff ....
Event backend in use: epoll
==== LPC Predefines ====
#define FLUFFOS
#define HAS_DEBUG_LEVEL
#define HAS_ED
#define HAS_PRINTF
#define MAX_FLOAT 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000
#define MAX_INT 9223372036854775807
#define MIN_FLOAT 0.000000
#define MIN_INT -9223372036854775808
#define MUDOS
#define MUD_NAME "Threshold"
#define SIZEOFINT 8
#define __ARCH__ "Linux/x86-64"
#define __ARGUMENTS_IN_TRACEBACK__
#define __ARRAY_STATS__
#define __AUTO_SETEUID__
#define __CACHE_STATS__
#define __CALLOUT_HANDLES__
#define __CFG_COMPILER_STACK_SIZE__ 600
#define __CFG_EVALUATOR_STACK_SIZE__ 65536
#define __CFG_LIVING_HASH_SIZE__ 256
#define __CFG_MAX_CALL_DEPTH__ 150
#define __CFG_MAX_GLOBAL_VARIABLES__ 65536
#define __CLASS_STATS__
#define __COMMAND_BUF_SIZE__ 2000
#define __COMPILER__ "/usr/bin/c++"
#define __CXXFLAGS__ "Broken"
#define __DEBUG_MACRO__
#define __DEFAULT_DB__ 1
#define __DEFAULT_PRAGMAS__ PRAGMA_SAVE_TYPES + PRAGMA_ERROR_CONTEXT + PRAGMA_OPTIMIZE
#define __DSLIB__
#define __ED_INDENT_SPACES__ 4
#define __ED_TAB_WIDTH__ 8
#define __GET_CHAR_IS_BUFFERED__
#define __HAS_CONSOLE__
#define __HAVE_DIRENT_H__ 1
#define __HAVE_JEMALLOC__ 1
#define __HAVE_SIGNAL_H__ 1
#define __HAVE_SYS_RESOURCE_H__ 1
#define __HAVE_SYS_STAT_H__ 1
#define __HAVE_SYS_TIME_H__ 1
#define __HAVE_TIME_H__ 1
#define __LARGEST_PRINTABLE_STRING__ 65535
#define __LARGE_STRING_SIZE__ 1000
#define __LOCALS_IN_TRACEBACK__
#define __MAX_SAVE_SVALUE_DEPTH__ 100
#define __MUDLIB_ERROR_HANDLER__
#define __OLD_ED__
#define __PACKAGES_PACKAGES_H__
#define __PACKAGE_ASYNC__
#define __PACKAGE_COMPRESS__
#define __PACKAGE_CONTRIB__
#define __PACKAGE_CORE__
#define __PACKAGE_CRYPTO__
#define __PACKAGE_DB__
#define __PACKAGE_DEVELOP__
#define __PACKAGE_EXTERNAL__
#define __PACKAGE_MATH__
#define __PACKAGE_MATRIX__
#define __PACKAGE_OPS__
#define __PACKAGE_PARSER__
#define __PACKAGE_PCRE__
#define __PACKAGE_SHA1__
#define __PACKAGE_SOCKETS__
#define __PACKAGE_TRIM__
#define __PACKAGE_UIDS__
#define __PARSE_DEBUG__
#define __PORT__ 3333
#define __PRIVS__
#define __PROJECT_VERSION__ "fluffos v2019.2020091001"
#define __RANDOMIZED_RESETS__
#define __RECEIVE_SNOOP__
#define __REF_RESERVED_WORD__
#define __RESTRICTED_ED__
#define __SANE_EXPLODE_STRING__
#define __SANE_SORTING__
#define __SAVE_EXTENSION__ ".o"
#define __SAVE_GZ_EXTENSION__ ".o.gz"
#define __SENSIBLE_MODIFIERS__
#define __SMALL_STRING_SIZE__ 100
#define __STRING_STATS__
#define __STRUCT_CLASS__
#define __STRUCT_STRUCT__
#define __SUPPRESS_ARGUMENT_WARNINGS__
#define __THIS_PLAYER_IN_CALL_OUT__
#define __TIME_WITH_SYS_TIME__ 1
#define __TRACE__
#define __TRAP_CRASHES__
#define __USE_32BIT_ADDRESSES__
#define __USE_MYSQL__ 1
#define __VERSION__ "fluffos v2019.2020091001"
#define __WARN_OLD_RANGE_BEHAVIOR__
========================
Loading simul_efun file : /adm/obj/simul_efun
Loading master file: /adm/obj/master

Loading preload files ...
/adm/daemons/emoted...
/adm/daemons/event...
/adm/daemons/event_ic...
/adm/daemons/logind...
/adm/daemons/usage_d...
/adm/daemons/weather_d.c...
/adm/daemons/channels...
/adm/daemons/boot_d...
/adm/daemons/register_update...
/adm/daemons/color_d...
/adm/daemons/global_funcs...
/adm/daemons/toggle...
Accepting telnet connections on 0.0.0.0:3333.
Initializations complete.

old crypt() password detected, It is only using first 2 character as key and ignore password beyond 8 characters, please upgrade to SHA512 using crypt(password) immediately.
old crypt() password detected, It is only using first 2 character as key and ignore password beyond 8 characters, please upgrade to SHA512 using crypt(password) immediately.
old crypt() password detected, It is only using first 2 character as key and ignore password beyond 8 characters, please upgrade to SHA512 using crypt(password) immediately.

Program received signal SIGSEGV, Segmentation fault.
0x000055555563a9aa in assign_svalue_no_free (to=0x555555799610 <_ZL6_stack.lto_priv.0+208>,
    from=0x5555557995f0 <_ZL6_stack.lto_priv.0+176>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/base/svalue.cc:37
37            INC_COUNTED_REF(to->u.string);
(gdb) bt
#0  0x000055555563a9aa in assign_svalue_no_free (to=0x555555799610 <_ZL6_stack.lto_priv.0+208>,
    from=0x5555557995f0 <_ZL6_stack.lto_priv.0+176>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/base/svalue.cc:37
#1  0x00005555556526af in eval_instruction (p=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/base/interpret.cc:2271
#2  0x000055555563fe13 in apply_low (fun=<optimized out>, ob=<optimized out>, num_arg=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:270
#3  0x00005555556411ab in apply (where=<optimized out>, num_arg=1, ob=<optimized out>, fun=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:325
#4  safe_apply (fun=<optimized out>, ob=<optimized out>, num_arg=1, where=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:325
#5  0x00005555555c0239 in call_callback (fd=<optimized out>, what=64, num_arg=1)
    at /usr/include/c++/9/bits/stl_deque.h:273
#6  0x00005555555c53ba in socket_write_select_handler (fd=2)
    at /frogdice/thresh_fluffos/fluffos/src/packages/sockets/socket_efuns.cc:1259
#7  (anonymous namespace)::on_lpc_sock_write (fd=<optimized out>, what=<optimized out>, arg=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/packages/sockets/socket_efuns.cc:47
#8  0x00007ffff6de2fde in ?? () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#9  0x00007ffff6de387f in event_base_loop () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#10 0x0000555555687308 in backend (base=0x7ffff4ecc000) at /frogdice/thresh_fluffos/fluffos/src/backend.cc:225
#11 driver_main (argc=<optimized out>, argv=<optimized out>) at /frogdice/thresh_fluffos/fluffos/src/mainlib.cc:414
#12 0x0000555555578019 in main (argc=<optimized out>, argv=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/main.cc:5
(gdb) info locals
No locals.
(gdb)
```

**Comment by gesslar** [comment]
Sanitizer output
```
==29338==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fffffff1180 at pc 0x7ffff7601cbd bp 0x7fffffff1100 sp 0x7fffffff08a8
READ of size 25 at 0x7fffffff1180 thread T0
    #0 0x7ffff7601cbc  (/lib/x86_64-linux-gnu/libasan.so.5+0x74cbc)
    #1 0x55555678c931 in strchr /usr/include/string.h:221
    #2 0x55555678c931 in f_ctime() /frogdice/thresh_fluffos/fluffos/src/packages/core/efuns_main.cc:439
    #3 0x5555569f01ac in eval_instruction(char*) /frogdice/thresh_fluffos/fluffos/src/vm/internal/base/interpret.cc:3774    #4 0x555556945090 in apply_low(char const*, object_t*, int) /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:270
    #5 0x55555679c4c9 in apply(char const*, object_t*, int, int) /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:296
    #6 0x55555679c4c9 in f__call_other() /frogdice/thresh_fluffos/fluffos/src/packages/core/efuns_main.cc:221
    #7 0x5555569f01ac in eval_instruction(char*) /frogdice/thresh_fluffos/fluffos/src/vm/internal/base/interpret.cc:3774    #8 0x555556945090 in apply_low(char const*, object_t*, int) /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:270
    #9 0x55555694eebe in apply(char const*, object_t*, int, int) /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:296
    #10 0x55555694eebe in safe_apply(char const*, object_t*, int, int) /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:325
    #11 0x555556c4b618 in call_function_interactive /frogdice/thresh_fluffos/fluffos/src/comm.cc:1411
    #12 0x555556c4b618 in process_user_command(interactive_t*) /frogdice/thresh_fluffos/fluffos/src/comm.cc:1163
    #13 0x555556c4b618 in on_user_command /frogdice/thresh_fluffos/fluffos/src/comm.cc:96
    #14 0x7ffff5db7fdd  (/lib/x86_64-linux-gnu/libevent-2.1.so.7+0x20fdd)
    #15 0x7ffff5db887e in event_base_loop (/lib/x86_64-linux-gnu/libevent-2.1.so.7+0x2187e)
    #16 0x555556bf1d55 in backend(event_base*) /frogdice/thresh_fluffos/fluffos/src/backend.cc:225
    #17 0x555556bf1d55 in driver_main /frogdice/thresh_fluffos/fluffos/src/mainlib.cc:414
    #18 0x5555562b4a68 in main /frogdice/thresh_fluffos/fluffos/src/main.cc:5
    #19 0x7ffff6a550b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #20 0x5555562b4acd in _start (/frogdice/thresh_fluffos/bin/driver+0xd60acd)

Address 0x7fffffff1180 is located in stack of thread T0 at offset 96 in frame
    #0 0x55555678c67f in f_ctime() /frogdice/thresh_fluffos/fluffos/src/packages/core/efuns_main.cc:429

  This frame has 4 object(s):
    [32, 40) 't' (line 429)
    [64, 72) 't' (line 429)
    [96, 351) 'buf' <== Memory access at offset 96 is inside this variable
    [416, 671) 'buf'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope (/lib/x86_64-linux-gnu/libasan.so.5+0x74cbc)
Shadow bytes around the buggy address:
  0x10007fff61e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff61f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff6200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff6210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff6220: 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2 00 f2 f2 f2
=>0x10007fff6230:[f8]f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x10007fff6240: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x10007fff6250: f2 f2 f2 f2 f2 f2 f2 f2 00 00 00 00 00 00 00 00
  0x10007fff6260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff6270: 00 00 00 00 00 00 00 07 f3 f3 f3 f3 f3 f3 f3 f3
  0x10007fff6280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==29338==ABORTING
[Inferior 1 (process 29338) exited with code 01]
```
