### ISSUE TITLE
segfault in v2019 parser.cc make_function(...) when handling WRD tokens

### ISSUE THREAD

**Issue by solidtechnology** [fluffos/fluffos#705]
Hello!

I had a reproducible crash on current v2019 on Ubuntu LTS.  lib is an old lima. It would segfault whenever it tried to parse a rule containing a WRD token.  I.e. a verb look with the tokens "WRD OBJ", would crash when "look in bag" was parsed.  

line 2085 of /packages/parser/parser.cc looks like this in the current v2019 branch:
```
      case WRD_TOKEN: {
        char tmp[1024];
        buf = strput(buf, end, "wrd");
        strput_words(tmp, end, matches[match].first, matches[match].last);
        push_malloced_string(string_copy(tmp, "push_real_names"));
        match++;
        on_stack++;
      } break;
```
I was able to blindly resolve this by changing the strput_words call so that it looked similar to the STR_TOKEN above it in the switch statement:
`strput_words(tmp, EndOf(tmp), matches[match].first, matches[match].last);` (line 2088 of parser.cc)

Here is the sanitizer output in GDB.
```
==940==ERROR: AddressSanitizer: negative-size-param: (size=-33)
    #0 0x7ffff6e91813  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79813)
    #1 0x55555628287d in memcpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
    #2 0x55555628287d in strput_words(char*, char*, int, int) [clone .lto_priv.868] /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:1399
    #3 0x55555629952b in make_function(char*, char*, int, parse_state_t*, int, object_t*) [clone .isra.8] [clone .lto_priv.913] /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:2088
    #4 0x55555629952b in check_functions /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:2119
    #5 0x55555629952b in we_are_finished /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:2750
    #6 0x5555562a4447 in parse_rule /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:2895
    #7 0x5555562a3e21 in parse_rule /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:2919
    #8 0x5555562a34f9 in parse_rule /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:2951
    #9 0x5555562a643d in parse_rules /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:3041
    #10 0x5555562a643d in parse_recurse /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:3111
    #11 0x5555562a6c4e in parse_recurse /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:3089
    #12 0x5555562a689c in parse_recurse /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:3078
    #13 0x5555562a689c in parse_recurse /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:3078
    #14 0x5555562a929c in parse_sentence(char const*) [clone .lto_priv.879] /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:3232
    #15 0x5555562fa5ba in f_parse_sentence() /srv/mud/desolation/fluffos-2019/driver/src/packages/parser/parser.cc:3332
    #16 0x5555560f663a in eval_instruction(char*) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/interpret.cc:3774
    #17 0x555556262899 in apply_low(char const*, object_t*, int) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/apply.cc:270
    #18 0x5555560da313 in apply /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/apply.cc:296
    #19 0x5555560da313 in f__call_other() /srv/mud/desolation/fluffos-2019/driver/src/packages/core/efuns_main.cc:221
    #20 0x5555560f663a in eval_instruction(char*) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/interpret.cc:3774
    #21 0x55555609c205 in call_function_pointer(funptr_t*, int) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/function.cc:306
    #22 0x5555562b6dd3 in f__evaluate() /srv/mud/desolation/fluffos-2019/driver/src/packages/ops/ops.cc:1230
    #23 0x5555560f663a in eval_instruction(char*) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/interpret.cc:3774
    #24 0x55555609c205 in call_function_pointer(funptr_t*, int) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/function.cc:306
    #25 0x55555609e84c in safe_call_function_pointer(funptr_t*, int) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/function.cc:340
    #26 0x555555e4b93d in call_function_interactive /srv/mud/desolation/fluffos-2019/driver/src/comm.cc:1413
    #27 0x555555e4b93d in process_user_command /srv/mud/desolation/fluffos-2019/driver/src/comm.cc:1163
    #28 0x555555e4b93d in on_user_command /srv/mud/desolation/fluffos-2019/driver/src/comm.cc:96
    #29 0x7ffff459ca10  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1ea10)
    #30 0x7ffff459d33e in event_base_loop (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1f33e)
    #31 0x555555e3eeaa in backend /srv/mud/desolation/fluffos-2019/driver/src/backend.cc:225
    #32 0x555555e3eeaa in driver_main /srv/mud/desolation/fluffos-2019/driver/src/mainlib.cc:430
    #33 0x555555dc2848 in main /srv/mud/desolation/fluffos-2019/driver/src/main.cc:5
    #34 0x7ffff5d27bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #35 0x555555dcc0b9 in _start (/srv/mud/desolation/fluffos-2019/build/bin/driver+0x8780b9)

0x604001093cac is located 28 bytes inside of 44-byte region [0x604001093c90,0x604001093cbc)
allocated by thread T0 here:
    #0 0x7ffff6ef6b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x555556306458 in int_new_string(unsigned int) /srv/mud/desolation/fluffos-2019/driver/src/base/internal/stralloc.cc:329
    #2 0x555556306816 in int_string_copy(char const*) /srv/mud/desolation/fluffos-2019/driver/src/base/internal/stralloc.cc:394
    #3 0x55555628c18c in f_range(int) /srv/mud/desolation/fluffos-2019/driver/src/packages/ops/ops.cc:672
    #4 0x5555560f330f in eval_instruction(char*) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/interpret.cc:3500
    #5 0x5555560f08ff in eval_instruction(char*) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/interpret.cc:3641
    #6 0x55555609c205 in call_function_pointer(funptr_t*, int) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/function.cc:306
    #7 0x5555562b6dd3 in f__evaluate() /srv/mud/desolation/fluffos-2019/driver/src/packages/ops/ops.cc:1230
    #8 0x5555560f663a in eval_instruction(char*) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/interpret.cc:3774
    #9 0x55555609c205 in call_function_pointer(funptr_t*, int) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/function.cc:306
    #10 0x55555609e84c in safe_call_function_pointer(funptr_t*, int) /srv/mud/desolation/fluffos-2019/driver/src/vm/internal/base/function.cc:340
    #11 0x555555e4b93d in call_function_interactive /srv/mud/desolation/fluffos-2019/driver/src/comm.cc:1413
    #12 0x555555e4b93d in process_user_command /srv/mud/desolation/fluffos-2019/driver/src/comm.cc:1163
    #13 0x555555e4b93d in on_user_command /srv/mud/desolation/fluffos-2019/driver/src/comm.cc:96
    #14 0x7ffff459ca10  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1ea10)

SUMMARY: AddressSanitizer: negative-size-param (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79813)
==940==ABORTING
[Inferior 1 (process 940) exited with code 01]
```

Before sanitizer, the crash looked like this:
```
Program received signal SIGSEGV, Segmentation fault.
__memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:534
534     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.


#1  0x616e6e5500000000 in ?? ()
#2  0x66666f435f64656d in ?? ()
#3  0x30312344554d6565 in ?? ()
#4  0x3132373936373937 in ?? ()
#5  0x0000000000000000 in ?? ()
```

I don't have a driver log from last night, but the config settings should be the same.  This is from this morning after turning sanitizer off:
```
Mon Nov 16 10:09:37 UTC 2020
========================================================================
Full Command Line: /srv/mud/desolation/fluffos-2019/build/bin/driver /srv/mud/desolation/bin/config-2019.lima
Boot Time: Mon Nov 16 10:09:37 2020
Version: fluffos v2019.2020101101-32-g23ac0980 (Linux/x86-64)
jemalloc Version: 3.6.0-11
ICU Version: 65.1
Backtrace support: libdw.
Core Dump: No, Max FD: 65535.
========================================================================
Final Debug Level: 0
Processing config file: /srv/mud/desolation/bin/config-2019.lima
maximum local variables: invalid new value, resetting to default.
Unable to open log file: "log/execute", error: "No such file or directory".
Initializing internal stuff ....
Event backend in use: epoll
==== Runtime Config Table ====
time to clean up : 7200 # default: 600
time to reset : 1800 # default: 900
time to swap : 1800 # default: 300
evaluator stack size : 1000 # default: 65536
inherit chain size : 130 # default: 30
maximum evaluation cost : 10000000 # default: 30000000
maximum local variables : 64
maximum call depth : 30 # default: 150
maximum array size : 32000 # default: 15000
maximum buffer size : 4000000 # default: 400000
maximum mapping size : 15000 # default: 150000
maximum string length : 200000
maximum bits in a bitfield : 1200 # default: 12000
maximum byte transfer : 100000 # default: 200000
maximum read file size : 2000000 # default: 200000
hash table size : 7001
object table size : 1501
living hash table size : 100 # default: 256
gametick msec : 1000
heartbeat interval msec : 1000
sane explode string : 1
reversible explode string : 0
sane sorting : 1
warn tab : 0
wombles : 0
call other type check : 0
call other warn : 0
mudlib error handler : 1
no resets : 0
lazy resets : 0
randomized resets : 1
no ansi : 1
strip before process input : 1
this_player in call_out : 1
trace : 1
trace code : 0
interactive catch tell : 0
receive snoop : 1
snoop shadowed : 0
reverse defer : 0
has console : 1
noninteractive stderr write : 1 # default: 0
trap crashes : 1
old type behavior : 0
old range behavior : 0
warn old range behavior : 1
suppress argument warnings : 1
enable_commands call init : 0 # default: 1
sprintf add_justified ignore ANSI colors : 1
call_out(0) nest level : 10 # default: 1000
trace lpc execution context : 0
trace lpc instructions : 0
enable mxp : 0
enable gmcp : 0
enable zmp : 0
enable mssp : 1
==============================
==== LPC Predefines ====
#define FLUFFOS
#define HAS_DEBUG_LEVEL
#define HAS_PRINTF
#define MAX_FLOAT 17976931348623157081452742373170435679807056752584499659891747680315726078002853876058955863276687817154045895351438246423432132688946
41827684675467035375169860499105765512820762454900903893289440758685084551339423045832369032229481658085593321233482747978262041447231687381771809192998
81250404026184124858368.000000
#define MAX_INT 9223372036854775807
#define MIN_FLOAT 0.000000
#define MIN_INT -9223372036854775808
#define MUDOS
#define MUD_NAME "Desolation"
#define SIZEOFINT 8
#define __ARCH__ "Linux/x86-64"
#define __ARGUMENTS_IN_TRACEBACK__
#define __ARRAY_STATS__
#define __AUTO_SETEUID__
#define __CACHE_STATS__
#define __CALLOUT_HANDLES__
#define __CFG_COMPILER_STACK_SIZE__ 600
#define __CFG_EVALUATOR_STACK_SIZE__ 65536
#define __CFG_LIVING_HASH_SIZE__ 256
#define __CFG_MAX_CALL_DEPTH__ 150
#define __CFG_MAX_GLOBAL_VARIABLES__ 65536
#define __CLASS_STATS__
#define __COMMAND_BUF_SIZE__ 2000
#define __COMPILER__ "/usr/bin/c++"
#define __CXXFLAGS__ "Broken"
#define __DEBUG_MACRO__
#define __DEFAULT_DB__ 1
#define __DEFAULT_PRAGMAS__ PRAGMA_WARNINGS + PRAGMA_SAVE_TYPES + PRAGMA_ERROR_CONTEXT + PRAGMA_OPTIMIZE
#define __DSLIB__
#define __ED_INDENT_SPACES__ 4
#define __ED_TAB_WIDTH__ 8
#define __GET_CHAR_IS_BUFFERED__
#define __HAS_CONSOLE__
#define __HAVE_DIRENT_H__ 1
#define __HAVE_JEMALLOC__ 1
#define __HAVE_SIGNAL_H__ 1
#define __HAVE_SYS_RESOURCE_H__ 1
#define __HAVE_SYS_STAT_H__ 1
#define __HAVE_SYS_TIME_H__ 1
#define __HAVE_TIME_H__ 1
#define __LARGEST_PRINTABLE_STRING__ 65535
#define __LARGE_STRING_SIZE__ 1000
#define __LOCALS_IN_TRACEBACK__
#define __MAX_SAVE_SVALUE_DEPTH__ 100
#define __MUDLIB_ERROR_HANDLER__
#define __NONINTERACTIVE_STDERR_WRITE__
#define __NO_ADD_ACTION__
#define __NO_LIGHT__
#define __NO_WIZARDS__
#define __PACKAGES_PACKAGES_H__
#define __PACKAGE_ASYNC__
#define __PACKAGE_COMPRESS__
#define __PACKAGE_CONTRIB__
#define __PACKAGE_CORE__
#define __PACKAGE_CRYPTO__
#define __PACKAGE_DB__
#define __PACKAGE_DEVELOP__
#define __PACKAGE_MATH__
#define __PACKAGE_MATRIX__
#define __PACKAGE_MUDLIB_STATS__
#define __PACKAGE_OPS__
#define __PACKAGE_PARSER__
#define __PACKAGE_PCRE__
#define __PACKAGE_SHA1__
#define __PACKAGE_SOCKETS__
#define __PACKAGE_TRIM__
#define __PARSE_DEBUG__
#define __PORT__ 8787
#define __PRIVS__
#define __PROJECT_VERSION__ "fluffos v2019.2020101101-32-g23ac0980"
#define __RANDOMIZED_RESETS__
#define __RECEIVE_SNOOP__
#define __REF_RESERVED_WORD__
#define __RESTRICTED_ED__
#define __SANE_EXPLODE_STRING__
#define __SANE_SORTING__
#define __SAVE_EXTENSION__ ".o"
#define __SAVE_GZ_EXTENSION__ ".o.gz"
#define __SENSIBLE_MODIFIERS__
#define __SMALL_STRING_SIZE__ 100
#define __STRING_STATS__
#define __STRUCT_CLASS__
#define __STRUCT_STRUCT__
#define __SUPPRESS_ARGUMENT_WARNINGS__
#define __THIS_PLAYER_IN_CALL_OUT__
#define __TIME_WITH_SYS_TIME__ 1
#define __TRACE__
#define __TRAP_CRASHES__
#define __USE_32BIT_ADDRESSES__
#define __USE_MYSQL__ 1
#define __VERSION__ "fluffos v2019.2020101101-32-g23ac0980"
#define __WARN_OLD_RANGE_BEHAVIOR__
========================
Loading simul_efun file : /secure/simul_efun
Loading master file: /secure/master
domain_file() in the master file does not work, using 'BACKBONE' as fallback (see domain_file.4)
author_file() in the master file does not work, using 'NONAME' as fallback (see author_file.4)

Loading preload files ...
/std/object...
/secure/user...
/obj/secure/shell...
/std/body/cmd...
/std/body...
/daemons/seasons_d...
/daemons/help_d...
/daemons/channel_d...
/daemons/keepalive_d...
/cmds/verbs/look...
/daemons/soul_d...
/daemons/imud_d...
/daemons/doc_d...
/secure/daemons/http_d...
/secure/daemons/ftp_d...
/daemons/chanlog_d...
/secure/daemons/imail_d...
/daemons/maintain_d...
/daemons/status_d...
/daemons/verb_d...
/daemons/alias_d...
/std/modules/m_glob...
Accepting websocket connections on 155.254.17.153:8787.
Accepting telnet connections on 155.254.17.153:7878.
Initializations complete.
```

Please let me know if you would like any additional details.  Thank you so much for supporting FluffOS.

**Comment by thefallentree** [comment]
Thanks for reporting! Do you have an minimal LPC test case that I can use ?

**Comment by thefallentree** [comment]
I can't really reproduce this issue, can you look at this test case and see how it is different ?

```
string id() {
  return "bag";
}

void create() {
  parse_init();

  if(clonep()) {
    move_object(__FILE__);
  }
}

void do_tests() {
#ifndef __PACKAGE_PARSER__
  write("no package parser, skipped.\n");
  return;
#else
  clone_object(__FILE__);
  clone_object(__FILE__);
  clone_object(__FILE__);
  write(sprintf("%O", all_inventory()) + "\n");
  parse_add_rule("look", "WRD OBJ");
  write(parse_dump() + "\n");
  ASSERT_EQ(1, parse_sentence("look in my bag", 2, all_inventory()));
#endif
}

```

**Comment by thefallentree** [comment]
ah this issue only appears in RELEASE build, interesting

**Comment by solidtechnology** [comment]
Sorry for the delayed response.  I didn't have a test case and finally sat down to look at building one, but it looks like you got it handled.  Appreciate it!
