### ISSUE TITLE
 signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by seikichin** [fluffos/fluffos#712]
(gdb) bt
#0  0x000000000070c3cb in ___chkstk_ms ()
    at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/comm.cc:120
#1  0x0000000000006558 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)

**Comment by thefallentree** [comment]
after debugging, real stacktrace is this

```
(gdb) bt
#0  load_object (lname=0x31b4fc0 "system/daemons/secure_d", callcreate=1) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:417
#1  0x000000000046ba33 in find_object (str=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:1474
#2  0x0000000000492559 in f__call_other () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/efuns_main.cc:215
#3  0x000000000043ab46 in eval_instruction (p=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:3774
#4  0x0000000000510905 in apply_master_ob(int, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:4107
#5  0x0000000000514847 in check_valid_path(char const*, object_t*, char const*, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/file.cc:599
#6  0x0000000000458965 in load_object (lname=0x31bd270 "system/daemons/secure_d", callcreate=1) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:429
#7  0x000000000046ba33 in find_object (str=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:1474
#8  0x0000000000492559 in f__call_other () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/efuns_main.cc:215
#9  0x000000000043ab46 in eval_instruction (p=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:3774
#10 0x0000000000510905 in apply_master_ob(int, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:4107
#11 0x0000000000514847 in check_valid_path(char const*, object_t*, char const*, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/file.cc:599
#12 0x0000000000458965 in load_object (lname=0x31c5520 "system/daemons/secure_d", callcreate=1) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:429
#13 0x000000000046ba33 in find_object (str=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:1474
#14 0x0000000000492559 in f__call_other () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/efuns_main.cc:215
#15 0x000000000043ab46 in eval_instruction (p=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:3774
#16 0x0000000000510905 in apply_master_ob(int, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:4107
#17 0x0000000000514847 in check_valid_path(char const*, object_t*, char const*, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/file.cc:599
#18 0x0000000000458965 in load_object (lname=0x31cd7d0 "system/daemons/secure_d", callcreate=1) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:429
#19 0x000000000046ba33 in find_object (str=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:1474
#20 0x0000000000492559 in f__call_other () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/efuns_main.cc:215
#21 0x000000000043ab46 in eval_instruction (p=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:3774
#22 0x0000000000510905 in apply_master_ob(int, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:4107
#23 0x0000000000514847 in check_valid_path(char const*, object_t*, char const*, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/file.cc:599
#24 0x0000000000458965 in load_object (lname=0x31d5a80 "system/daemons/secure_d", callcreate=1) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:429
#25 0x000000000046ba33 in find_object (str=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:1474
#26 0x0000000000492559 in f__call_other () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/efuns_main.cc:215
#27 0x000000000043ab46 in eval_instruction (p=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:3774
#28 0x0000000000510905 in apply_master_ob(int, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:4107
#29 0x0000000000514847 in check_valid_path(char const*, object_t*, char const*, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/file.cc:599
#30 0x0000000000458965 in load_object (lname=0x31ddd30 "system/daemons/secure_d", callcreate=1) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:429
#31 0x000000000046ba33 in find_object (str=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:1474
#32 0x0000000000492559 in f__call_other () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/efuns_main.cc:215
#33 0x000000000043ab46 in eval_instruction (p=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:3774
#34 0x0000000000510905 in apply_master_ob(int, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/base/interpret.cc:4107
#35 0x0000000000514847 in check_valid_path(char const*, object_t*, char const*, int) [clone .constprop.0] () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/file.cc:599
#36 0x0000000000458965 in load_object (lname=0x31e5fe0 "system/daemons/secure_d", callcreate=1) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:429
#37 0x000000000046ba33 in find_object (str=<optimized out>) at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/vm/internal/simulate.cc:1474
#38 0x0000000000492559 in f__call_other () at E:/msys64/home/95/stflu-fluffos-master/fluffos/src/packages/core/efuns_main.cc:215
```
