### ISSUE TITLE
buffer-overflow cause driver crash

### ISSUE THREAD

**Issue by seikichin** [fluffos/fluffos#727]
```
old crypt() password detected, It is only using first 2 character as key and ignore password beyond 8 characters, please upgrade to SHA512 using crypt(password) immediately.
/home/seiki/fluffos/src/comm.cc:978:33: runtime error: index 2048 out of bounds for type 'char [2048]'
/home/seiki/fluffos/src/comm.cc:978:69: runtime error: index 2048 out of bounds for type 'char [2048]'
=================================================================
==3444==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d0000b3fa8 at pc 0x000008f1edb4 bp 0x7ffffffe9790 sp 0x7ffffffe9780
READ of size 1 at 0x61d0000b3fa8 thread T0
    #0 0x8f1edb3 in first_cmd_in_buf /home/seiki/fluffos/src/comm.cc:978
    #1 0x8f1edb3 in get_user_command /home/seiki/fluffos/src/comm.cc:1011
    #2 0x8f1edb3 in process_user_command /home/seiki/fluffos/src/comm.cc:1101    #3 0x8f1edb3 in on_user_command /home/seiki/fluffos/src/comm.cc:96
    #4 0x7ffffbd7ea10  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1ea10)
    #5 0x7ffffbd7f33e in event_base_loop (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1f33e)
    #6 0x8daa5f8 in backend /home/seiki/fluffos/src/backend.cc:225
    #7 0x8daa5f8 in driver_main /home/seiki/fluffos/src/mainlib.cc:430
    #8 0x88b1e08 in main /home/seiki/fluffos/src/main.cc:5
    #9 0x7ffffd331b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #10 0x88b2d89 in _start (/home/seiki/fymud/bin/driver+0x8b2d89)

0x61d0000b3fa8 is located 0 bytes to the right of 2344-byte region [0x61d0000b3680,0x61d0000b3fa8)
allocated by thread T0 here:
    #0 0x7ffffe51eb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x8ef701f in user_add /home/seiki/fluffos/src/user.cc:25
    #2 0x8ef701f in new_user(port_def_t*, int, sockaddr*, unsigned int) /home/seiki/fluffos/src/comm.cc:230
    #3 0x8ef9af5 in (anonymous namespace)::new_user_handler(evconnlistener*, int, sockaddr*, int, void*) [clone .lto_priv.1414] /home/seiki/fluffos/src/comm.cc:203
    #4 0x7ffffbd87190  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x27190)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/seiki/fluffos/src/comm.cc:978 in first_cmd_in_buf
```

**Comment by thefallentree** [comment]
fixed in #729
