### ISSUE TITLE
用最新编译的LIB在WSL下crash的问题

### ISSUE THREAD

**Issue by oiuv** [fluffos/fluffos#957]
使用最新的驱动运行我的炎黄MUD在登录时就crash了，日志如下：

```log

Accepting telnet connections on 0.0.0.0:5566.
Accepting telnet connections on 0.0.0.0:6666.
Accepting websocket connections on 0.0.0.0:8888.
Initializations complete.

/root/fluffos/src/packages/core/rc.cc:15:24: runtime error: index 256 out of bounds for type 'char *[255]'
/root/fluffos/src/packages/core/rc.cc:15:24: runtime error: load of address 0x7fd9fbb624a0 with insufficient space for an object of type 'char *'
0x7fd9fbb624a0: note: pointer points here
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^
=================================================================
==1347==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7fd9fbb624a0 at pc 0x7fd9f994b79e bp 0x7fffff21a200 sp 0x7fffff21a1f0
READ of size 8 at 0x7fd9fbb624a0 thread T0
    #0 0x7fd9f994b79d in get_config_item(svalue_t*, svalue_t*) /root/fluffos/src/packages/core/rc.cc:15
    #1 0x7fd9f994ba73 in f_get_config() /root/fluffos/src/packages/core/rc.cc:28
    #2 0x7fd9f95ef66d in eval_instruction(char*) /root/fluffos/src/vm/internal/base/interpret.cc:3791
    #3 0x7fd9f96a545c in apply_low(char const*, object_t*, int) /root/fluffos/src/vm/internal/apply.cc:267
    #4 0x7fd9f96a5697 in apply(char const*, object_t*, int, int) /root/fluffos/src/vm/internal/apply.cc:293
    #5 0x7fd9f96762fd in call_create(object_t*, int) /root/fluffos/src/vm/internal/base/object.cc:1961
    #6 0x7fd9f96d0d65 in load_object(char const*, int) /root/fluffos/src/vm/internal/simulate.cc:574
    #7 0x7fd9f96dc222 in find_object(char const*) /root/fluffos/src/vm/internal/simulate.cc:1473
    #8 0x7fd9f98d98d4 in f__call_other() /root/fluffos/src/packages/core/efuns_main.cc:220
    #9 0x7fd9f95ef66d in eval_instruction(char*) /root/fluffos/src/vm/internal/base/interpret.cc:3791
    #10 0x7fd9f96a545c in apply_low(char const*, object_t*, int) /root/fluffos/src/vm/internal/apply.cc:267
    #11 0x7fd9f96a5697 in apply(char const*, object_t*, int, int) /root/fluffos/src/vm/internal/apply.cc:293
    #12 0x7fd9f96a5968 in safe_apply(char const*, object_t*, int, int) /root/fluffos/src/vm/internal/apply.cc:322
    #13 0x7fd9f97154fe in call_function_interactive /root/fluffos/src/comm.cc:1435
    #14 0x7fd9f9712295 in process_user_command(interactive_t*) /root/fluffos/src/comm.cc:1200
    #15 0x7fd9f96ff931 in on_user_command /root/fluffos/src/comm.cc:99
    #16 0x7fd9f9d2da54 in event_process_active_single_queue /root/fluffos/src/thirdparty/libevent/event.c:1713
    #17 0x7fd9f9d2f6a8 in event_process_active /root/fluffos/src/thirdparty/libevent/event.c:1805
    #18 0x7fd9f9d3267e in event_base_loop /root/fluffos/src/thirdparty/libevent/event.c:2047
    #19 0x7fd9f96efa1f in backend(event_base*) /root/fluffos/src/backend.cc:239
    #20 0x7fd9f93c93f7 in driver_main /root/fluffos/src/mainlib.cc:435
    #21 0x7fd9f93c636c in main /root/fluffos/src/main.cc:5
    #22 0x7fd9f3ba4082 in __libc_start_main ../csu/libc-start.c:308
    #23 0x7fd9f93c628d in _start (/usr/local/games/driver+0x15f428d)

0x7fd9fbb624a0 is located 8 bytes to the right of global variable 'config_str' defined in '/root/fluffos/src/base/internal/rc.cc:25:7' (0x7fd9fbb61ca0) of size 2040
0x7fd9fbb624a0 is located 32 bytes to the left of global variable 'config_int' defined in '/root/fluffos/src/base/internal/rc.cc:26:5' (0x7fd9fbb624c0) of size 1020
SUMMARY: AddressSanitizer: global-buffer-overflow /root/fluffos/src/packages/core/rc.cc:15 in get_config_item(svalue_t*, svalue_t*)
Shadow bytes around the buggy address:
  0x0ffbbf764440: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffbbf764450: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffbbf764460: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffbbf764470: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffbbf764480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ffbbf764490: 00 00 00 f9[f9]f9 f9 f9 00 00 00 00 00 00 00 00
  0x0ffbbf7644a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffbbf7644b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffbbf7644c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffbbf7644d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffbbf7644e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1347==ABORTING
```

同样的代码，同一个版本的驱动，在windows下正常，好奇怪呀~

**Comment by oiuv** [comment]
在Ubuntu下测试也挂了，日志如下：

```log
Accepting telnet connections on 0.0.0.0:5566.
Accepting telnet connections on 0.0.0.0:6666.
Accepting websocket connections on 0.0.0.0:8888.
Initializations complete.

Stack trace (most recent call last):
#17   Object "", at 0xffffffffffffffff, in
#16   Object "/usr/games/driver", at 0x563e92210c49, in _start
#15   Object "/lib/x86_64-linux-gnu/libc-2.27.so", at 0x7f9ff5948c86, in __libc_start_main
#14   Source "/usr/local/games/fluffos/src/main.cc", line 5, in main [0x563e9220f438]
          2: extern "C" {
          3: int driver_main(int argc, char **argv);
          4: }
      >   5: int main(int argc, char **argv) { driver_main(argc, argv); }
#13 | Source "/usr/local/games/fluffos/src/mainlib.cc", line 435, in backend
    |   433:   debug_message("Initializations complete.\n\n");
    |   434:   setup_signal_handlers();
    | > 435:   backend(base);
    |   436:
    |   437:   return 0;
      Source "/usr/local/games/fluffos/src/backend.cc", line 239, in driver_main [0x563e9221b591]
        236:   event_add(g_ev_tick, &t);
        237:
        238:   try {
      > 239:     event_base_loop(base, 0);
        240:   } catch (...) {  // catch everything
        241:     fatal("BUG: jumped out of event loop!");
        242:   }
#12   Source "/usr/local/games/fluffos/src/thirdparty/libevent/event.c", line 2047, in event_base_loop [0x563e9221dba7]
       2044:            timeout_process(base);
       2045:
       2046:            if (N_ACTIVE_CALLBACKS(base)) {
      >2047:                    int n = event_process_active(base);
       2048:                    if ((flags & EVLOOP_ONCE)
       2049:                        && N_ACTIVE_CALLBACKS(base) == 0
       2050:                        && n != 0)
#11   Source "/usr/local/games/fluffos/src/thirdparty/libevent/event.c", line 1805, in event_process_active [0x563e9221d6ce]
       1802:                    base->event_running_priority = i;
       1803:                    activeq = &base->activequeues[i];
       1804:                    if (i < limit_after_prio)
      >1805:                            c = event_process_active_single_queue(base, activeq,
       1806:                                INT_MAX, NULL);
       1807:                    else
       1808:                            c = event_process_active_single_queue(base, activeq,
#10   Source "/usr/local/games/fluffos/src/thirdparty/libevent/event.c", line 1713, in event_process_active_single_queue.isra.29 [0x563e92310bdb]
       1710:                    evcb_callback = *ev->ev_callback;
       1711:                    res = ev->ev_res;
       1712:                    EVBASE_RELEASE_LOCK(base, th_base_lock);
      >1713:                    evcb_callback(ev->ev_fd, res, ev->ev_arg);
       1714:            }
       1715:            break;
       1716:            case EV_CLOSURE_CB_SELF: {
#9  | Source "/usr/local/games/fluffos/src/comm.cc", line 99, in process_user_command
    |    97:   set_eval(max_eval_cost);
    |    98:   try {
    | >  99:     process_user_command(user);
    |   100:   } catch (const char *) {
    |   101:     restore_context(&econ);
    | Source "/usr/local/games/fluffos/src/comm.cc", line 1200, in call_function_interactive
    |  1198: #endif
    |  1199: #if defined(F_INPUT_TO) || defined(F_GET_CHAR)
    | >1200:   if (call_function_interactive(ip, user_command)) {
    |  1201:     goto exit;
    |  1202:   }
      Source "/usr/local/games/fluffos/src/comm.cc", line 1435, in on_user_command [0x563e922c62ef]
       1432:       if (function[0] == APPLY___INIT_SPECIAL_CHAR) {
       1433:         error("Illegal function name.\n");
       1434:       }
      >1435:       (void)safe_apply(function, ob, num_arg + 1, ORIGIN_INTERNAL);
       1436:     } else {
       1437:       safe_call_function_pointer(funp, num_arg + 1);
       1438:     }
#8  | Source "/usr/local/games/fluffos/src/vm/internal/apply.cc", line 322, in apply
    |   320:   svalue_t *ret = nullptr;
    |   321:   try {
    | > 322:     ret = apply(fun, ob, num_arg, where);
    |   323:   } catch (const char *) {
    |   324:     restore_context(&econ);
      Source "/usr/local/games/fluffos/src/vm/internal/apply.cc", line 293, in safe_apply [0x563e9231ef21]
        290: #ifdef DEBUG
        291:   expected_sp = sp - num_arg;
        292: #endif
      > 293:   if (apply_low(fun, ob, num_arg) == 0) {
        294:     return nullptr;
        295:   }
        296:   free_svalue(&apply_ret_value, "sapply");
#7    Source "/usr/local/games/fluffos/src/vm/internal/apply.cc", line 267, in apply_low [0x563e9231d510]
        264: #ifdef DEBUG
        265:     save_csp = csp;
        266: #endif
      > 267:     call_program(current_prog, funp->address);
        268:     DEBUG_CHECK(save_csp - 1 != csp, "Bad csp after execution in apply_low.\n");
        269:     return 1;
        270:   }
#6    Source "/usr/local/games/fluffos/src/vm/internal/base/interpret.cc", line 3791, in eval_instruction [0x563e9222d71b]
       3789:           ScopedTracer _efun_tracer(instrs[instruction].name, EventCategory::LPC_EFUN,
       3790:                                     [&] { return trace_context; });
      >3791:           (*efun_table[instruction - EFUN_BASE])();
       3792:         }
       3793:
       3794: #ifdef DEBUG
#5    Source "/usr/local/games/fluffos/src/packages/core/efuns_main.cc", line 220, in f__call_other [0x563e922b9c23]
        217:     sp->u.arr = ret;
        218:     return;
        219:   } else {
      > 220:     ob = find_object(arg[0].u.string);
        221:     if (!ob || !object_visible(ob)) {
        222:       error("call_other() couldn't find object '%s'.\n", arg[0].u.string);
        223:     }
#4    Source "/usr/local/games/fluffos/src/vm/internal/simulate.cc", line 1473, in find_object [0x563e923505bc]
       1470:   if ((ob = ObjectTable::instance().find(tmpbuf))) {
       1471:     return ob;
       1472:   }
      >1473:   ob = load_object(tmpbuf, 1);
       1474:   if (!ob || (ob->flags & O_DESTRUCTED)) { /* *sigh* */
       1475:     return nullptr;
       1476:   }
#3    Source "/usr/local/games/fluffos/src/vm/internal/simulate.cc", line 574, in load_object [0x563e92258b98]
        571:   }
        572:
        573:   if (init_object(ob) && callcreate) {
      > 574:     call_create(ob, 0);
        575:   }
        576:   if (!(ob->flags & O_DESTRUCTED) && function_exists(APPLY_CLEAN_UP, ob, 1)) {
        577:     ob->flags |= O_WILL_CLEAN_UP;
#2  | Source "/usr/local/games/fluffos/src/vm/internal/base/object.cc", line 1961, in apply
    |  1959:   }
    |  1960:
    | >1961:   apply(APPLY_CREATE, ob, num_arg, ORIGIN_DRIVER);
    |  1962:
    |  1963:   ob->flags |= O_RESET_STATE;
      Source "/usr/local/games/fluffos/src/vm/internal/apply.cc", line 293, in call_create [0x563e9231f1db]
        290: #ifdef DEBUG
        291:   expected_sp = sp - num_arg;
        292: #endif
      > 293:   if (apply_low(fun, ob, num_arg) == 0) {
        294:     return nullptr;
        295:   }
        296:   free_svalue(&apply_ret_value, "sapply");
#1    Source "/usr/local/games/fluffos/src/vm/internal/apply.cc", line 267, in apply_low [0x563e9231d510]
        264: #ifdef DEBUG
        265:     save_csp = csp;
        266: #endif
      > 267:     call_program(current_prog, funp->address);
        268:     DEBUG_CHECK(save_csp - 1 != csp, "Bad csp after execution in apply_low.\n");
        269:     return 1;
        270:   }
#0    Source "/usr/local/games/fluffos/src/vm/internal/base/interpret.cc", line 2327, in eval_instruction [0x563e92232a5f]
       2324:               case T_STRING: {
       2325:                 char buff[100];
       2326:                 sprintf(buff, "%" LPC_INT_FMTSTR_P, (sp + 1)->u.number);
      >2327:                 EXTEND_SVALUE_STRING(sp, buff, "f_add: 2");
       2328:                 break;
       2329:               }
       2330:               default:
Segmentation fault (Address not mapped to object [0x6])
[1]    8832 segmentation fault  driver config.ini
```

游戏代码：https://github.com/oiuv/mud

**Comment by oiuv** [comment]
个人退回版本编译测试，在commit  a9133969e6cd27293af2c02c3d480c2c419466b3 开始崩溃的。
